### ISSUE TITLE
Mysterious JSON.parse error when running a background job

### ISSUE THREAD

**Issue by tkambler** [andris9/node-gearman#14]
[Example](https://gist.github.com/tkambler/0fc87d9c14de6dc7dfa8)

I pass stringified objects to all of my workers. Those workers then parse the payload, do their thing, then return their result as a stringified object, which the recipient then parses.

This works great, when submitting a standard job. I'm encountering a mysterious issue when running background jobs, though (see above example).

For a foreground job, the incoming worker payload looks like this:

```
Incoming doSomething job <Buffer 7b 22 61 6e 69 6d 61 6c 73 22 3a 5b 22 63 61 74 73 22 2c 22 64 6f 67 73 22 5d 7d>
```

For a background job, the incoming worker payload looks like this:

```
Incoming doSomething job <Buffer 7b 22 61 6e 69 6d 61 6c 73 22 3a 5b 22 63 61 74 73 22 2c 22 64 6f 67 73 22 5d 7d 00>
```

Note the extra `00` on the tail end there. This is causing my JSON to fail to be parsed, even though it looks identical. Any idea what's going on here?

**Comment by andris9** [comment]
I haven't used gearman nor this module for 3 years by now so I don't know if it's a bug or a protocol issue
